
name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            python -m pytest -p no:homeassistant tests/pytest/test_databases.py

  bats:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bats tests/bats
